from .variational_inference import VariationalInference
from .proximity_variational_inference import ProximityVariationalInference
from .annealing_variational_inference import AnnealingVariationalInference
from .proximity_update_variational_inference import ProximityUpdateVariationalInference
