from .deep_latent_gaussian_model import DeepLatentGaussianModel
from .deep_latent_gaussian_variational import DeepLatentGaussianVariational
# from .logistic_regression import LogisticRegressionModel
# from .logistic_regression_variational import LogisticRegressionVariational
from .sigmoid_belief_network import SigmoidBeliefNetworkModel
from .sigmoid_belief_network_variational import SigmoidBeliefNetworkVariational
